---
name: Build and check link

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: repo2docker install
        run: pip install --upgrade jupyter-repo2docker
      - name: sphinx install
        run: pip install --upgrade sphinx
      - name: Build container
        run: repo2docker --no-run .
      - name: Build docs
        run: |
           cd docs
           make clean html linkcheck
